### PR TITLE
add mdx dimension properties

### PR DESCRIPTION
**Pull request by vishn90**
Updated mdx dimension properties to get attribute for a dimension

### CODE REVIEW

**Comment by MariusWirtz** [comment]
Nice work @vishn90!
I'm very happy to finally introduce this feature to mdxpy.

However, before we merge this PR I would like to request a small change.

currently, you gather all properties that are requested and add them after the WHERE block in the MDX.
That's not really ideal I think.

I think it would be more convenient if we could request properties by axis. Please see the sample below. It produces the below df in conjunction with TM1py.

```
    SELECT
    {[d3].[e01]} DIMENSION PROPERTIES [d3].[d3].[attr1] ON 0 ,
    {TM1FILTERBYLEVEL({TM1SUBSETALL([d4].[d4])},0)} DIMENSION PROPERTIES MEMBER_NAME ON 1
    FROM [c4]
    WHERE ([d5].[e01])
```

|    | d4   | d3   | attr1   |   Value |
|---:|:-----|:-----|:--------|--------:|
|  0 | e01  | e01  | d       |       8 |
|  1 | e02  | e01  | d       |       8 |
|  2 | e03  | e01  | d       |       8 |

With your suggested implementation, all we could do is this. And it produces a less ideal output.

```
    SELECT
    {[d3].[e01]} ON 0 ,
    {TM1FILTERBYLEVEL({TM1SUBSETALL([d4].[d4])},0)} ON 1
    FROM [c4]
    WHERE ([d5].[e01])
    DIMENSION PROPERTIES [d3].[d3].[attr1] 
```

|    | d4   | Caption   | d3   | attr1   |   Value |
|---:|:-----|:----------|:-----|:--------|--------:|
|  0 | e01  | e01       | e01  | d       |       8 |
|  1 | e02  | e02       | e01  | d       |       8 |
|  2 | e03  | e03       | e01  | d       |       8 |

**Comment by vishn90** [comment]
Hi Marius,

Thanks for reviewing the solution!

Understand that we normally add the attributes to the axis but in my opinion thought post creating the entire query one could decide on the attributes that needs to be added in the end of the query which would be more convenient and easy to read and separate the attributes section. Also, I have tested that the DIMENSION PROPERTIES is not dependent on the axis as in couple of tests even the dimensions in axis 0 or 1 , if we add the DIMESION PROPERTIES at the end it pulls the attributes for both the axis's. 


mdx = MdxBuilder.from_cube("cube") \
            .rows_non_empty() \
            .add_hierarchy_set_to_row_axis(MdxHierarchySet.all_leaves("Dim1")) \
            .columns_non_empty() \
            .add_hierarchy_set_to_column_axis(MdxHierarchySet.member(Member.of("Dim2", "Elem2"))) \
            .where(Member.of("Dim3", "Elem3"), Member.of("Dim4", "Elem4")) \
            .properties(SetAttribute.of("Dim3", "Code and Name"), SetAttribute.of("Dim4", "version")) \
            .to_mdx()

As per the above query, have added two attributes and tested the output which works as expected.

I can look for attributes attaching to axis but before that want to understand from the below query (as per your comment) how the caption column is showing in the output? 

 
d4 | Caption | d3 | attr1 | Value
-- | -- | -- | -- | --
0 | e01 | e01 | e01 | d | 8
1 | e02 | e02 | e01 | d | 8
2 | e03 | e03 | e01 | d | 8

Solution for the query would be something like this:

mdx_query = 
  SELECT
    {[d3].[e01]}ON 0 ,
    {TM1FILTERBYLEVEL({TM1SUBSETALL([d4].[d4])},0)}  ON 1
    FROM [c4]
    WHERE ([d5].[e01])
     DIMENSION PROPERTIES [d3].[d3].[attr1] ,[d4].[d4].[MEMBER_NAME]

Using this query along with tm1py function - execute_mdx_dataframe_shaped(mdx_query, display_attributes = True) works perfect in my dev environment. 

correct me if I am wrong in understanding or missing something here. Thanks!

**Comment by MariusWirtz** [comment]
I agree with the idea that it's tidy to keep the attributes at the bottom.

However, if you add attributes at the bottom, the TM1 REST API will return all attributes for dimensions on which you didn't request properties.
At least that's how the TM1py function `execute_mdx_dataframe` behaves. Perhaps you could also resolve the problem in TM1py _(I think it's a REST API thing though)_?
But as long as this limitation persists, it is more efficient to specify attributes explicitly on the axes.


> I can look for attributes attaching to axis but before that want to understand from the below query (as per your comment) how the caption column is showing in the output?

When you use the `execute_mdx_dataframe` function, the returned data frame looks like the one in my sample above:

``` python 
from TM1py.Services.TM1Service import TM1Service

with TM1Service(base_url="https://localhost:12354", user="admin", password="apple") as tm1:
    mdx = """
    SELECT
    {[d3].[e01]} ON 0 ,
    {TM1FILTERBYLEVEL({TM1SUBSETALL([d4].[d4])},0)} ON 1
    FROM [c4]
    WHERE ([d5].[e01])
    DIMENSION PROPERTIES [d3].[d3].[attr1] 
    """

    df = tm1.cells.execute_mdx_dataframe(mdx, include_attributes=True)

    print(df.to_markdown())

```


Regarding tidyness and readability, I think the mdxpy query could still be fairly tidy and readable.
I guess we would end up with something like this

``` python
mdx = MdxBuilder.from_cube("cube")
.rows_non_empty()
.add_hierarchy_set_to_row_axis(MdxHierarchySet.all_leaves("Dim1"))
.columns_non_empty()
.add_hierarchy_set_to_column_axis(MdxHierarchySet.member(Member.of("Dim2", "Elem2")))
.where(Member.of("Dim3", "Elem3"), Member.of("Dim4", "Elem4"))
.add_property_to_column_axis(SetAttribute.of("Dim2", "Code and Name"))
.add_property_to_row_axis(SetAttribute.of("Dim1", "Version"))
.to_mdx()
```

**Comment by vishn90** [comment]
@MariusWirtz 

Sure, let me review mdxpy by putting the properties on axis. For me execute_mdx_dataframe with include attributes always throws error as we have around 10-15 attributes for each dimension, so always preferred execute_mdx_dataframe_shaped for attributes. 

Let me look into this further on mdxpy and tm1py front over the weekend and will get back to you.Thanks Marius!!

**Comment by MariusWirtz** [comment]
Yeah. The `execute_mdx_dataframe` function requires you to explicitly state the attributes you want to retrieve.
It can't handle the somewhat arbitrary response that TM1 provides when no attributes are requested explicitly.

You can read more about it here https://github.com/cubewise-code/tm1py/issues/718 and here https://github.com/cubewise-code/tm1py/pull/746

Thanks! I appreciate your contribution.
You might have to rebase this branch on the master again. There have been some changes to MDXpy in the meantime :)

**Comment by MariusWirtz** [comment]
closed in favor of #38

**Pull request closed without merging**
