### PR TITLE
added MdxRange

### PR DESCRIPTION
**Pull request by rclapp**
added new MdxRange class helpful for working with linear time dimensions

### CODE REVIEW

**Comment by MariusWirtz** [comment]
Thanks for the MR. I added some comments. 

Actually I'm a fan of rebasing in git, instead of merge. It brings the benefit of a "linear" history that is easier to understand. 
I can't **Rebase and Merge** this MR. I believe this has to do with 7301fc794523e2961c698e5e9de19db41f47e547.
In order for the **rebase and merge** to work, the features branches would always need to be based on the current cubewise-code/master branch.
We had the same issue last week with a MR from @mschlinz. 

Since mdxpy isn't really a complex project, I guess it doesn't make sense to enforce rebasing. 
I will change the policy in this project to allow merge-commits.
Then  I can merge your branch through a merge-commit.

Thanks for your contribution!

**Comment by rclapp** [comment]
Looks like this was never merged. Can you merge it?

**Comment by MariusWirtz** [comment]
Hi @rclapp,

I requested a few minor changes on the code https://github.com/cubewise-code/mdxpy/pull/11/files
If you don't have time I can also do the changes.

**Comment by rclapp** [comment]
updated pull request here: https://github.com/cubewise-code/mdxpy/pull/12

**Pull request closed without merging**
